
// main
#macro ADAPT_WIN_MOBILE_APPSURF		true
#macro ADAPT_WIN_MOBILE_GUI			true
#macro ADAPT_WIN_MOBILE_VIEW		7

#macro ADAPT_WIN_MOBILE_MODE		"h"

#macro ADAPT_WIN_MOBILE_W			1080
#macro ADAPT_WIN_MOBILE_H			1920

// virtual
#macro ADAPT_WIN_MOBILE_ASCPECT		true
#macro ADAPT_WIN_MOBILE_ASCPECT_W	1366
#macro ADAPT_WIN_MOBILE_ASCPECT_H	768

#macro ADAPT_WIN_MOBILE_MIN_W		1760
#macro ADAPT_WIN_MOBILE_MIN_H		990
