
// main
#macro ADAPT_WIN_MOBILE_APPSURF			true
#macro ADAPT_WIN_MOBILE_GUI				true
#macro ADAPT_WIN_MOBILE_VIEW			7
										
#macro ADAPT_WIN_MOBILE_MODE			"w"
#macro ADAPT_WIN_MOBILE_SIZE			1920

// virtual
#macro ADAPT_WIN_MOBILE_VIRT_ASCPECT	true
#macro ADAPT_WIN_MOBILE_VIRT_ASCPECT_W	720
#macro ADAPT_WIN_MOBILE_VIRT_ASCPECT_H	1460

#macro ADAPT_WIN_MOBILE_VIRT_MIN_W		1760
#macro ADAPT_WIN_MOBILE_VIRT_MIN_H		990

